# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux APFS filesystem routines.
#

obj-$(CONFIG_APFS_FS) += apfs.o

apfs-y := btree.o dir.o extents.o file.o inode.o key.o message.o namei.o \
	  node.o object.o spaceman.o super.o symlink.o transaction.o \
	  unicode.o xattr.o
