# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux APFS filesystem routines.
#

obj-$(CONFIG_APFS_FS) += apfs.o

apfs-y := btree.o dir.o file.o inode.o key.o message.o \
	  namei.o super.o symlink.o table.o xattr.o
